### ISSUE TITLE
How to change the browsers in the workflow?

### ISSUE THREAD

**Issue by kayjeiem** [alfredapp/launch-url-in-3-browsers-workflow#1]
I would like to use different browsers in this workflow, or perhaps even turn this workflow into a 6 browser workflow. How can i do that?

**Comment by thatcanadiangirl** [comment]
Once you've installed the workflow, take a look at the objects; You'll see three purple "Open URL" objects, set to Safari, Chrome and Firefox. You can double-click any of them to change which browser they open, or add more of the same to add more browsers you'd like to test.

**Comment by kayjeiem** [comment]
> 

thanks. let me test that out.
